apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: devops-template
  namespace: argo

spec:
  entrypoint: pipeline

  templates:

  - name: pipeline
    steps:
    - - name: deploy
        template: deploy

  - name: deploy
    container:
      image: bitnami/kubectl
      command: [sh, -c]
      args:
        - |
          cd /tmp

          echo "Cloning repo..."
          git clone https://github.com/Abhaysi0108/argo-devops-project.git

          cd argo-devops-project

          echo "Checking files:"
          ls

          echo "Deploying to Kubernetes..."
          kubectl apply -f deployment.yaml